### ISSUE TITLE
Setup pypi project for devicetree package

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/system-dt-playground#2]

**Comment by mbolivar-nordic** [comment]
https://python-devicetree.readthedocs.io/en/latest/
https://pypi.org/project/devicetree/0.0.1/
https://github.com/zephyrproject-rtos/python-devicetree/tree/v0.0.1 (edited) 


I've reserved a readthedocs page and packaged the current versions of these tools up so other people can use them. I had to tweak the sources and move things around a bit so we now have some forking maintenance to think about. I'm not committed to any of this but we should figure out how we're going to manage this soon IMO, probably just by taking the changes in python-devicetree back into the zephyr repo.
